kind: source
spec:
  name: "youtube"
  registry: "grpc"
  path: "localhost:7777"
#  tables: ["yt_country_metrics", "yt_channel_demographics", "yt_channel_metrics"]
#  tables: ["*"]
  tables: ["yt_video"]
  destinations: ["sqlite"]
  spec:
    concurrency: 1
    access_token: ${YT_ACCESS_TOKEN}
    channel_id: MINE
    start_date: 2022-01-01
    aggregate_unit: 1 # days
    results_per_query: 20
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite